version: "3.8"

services:
  db:
    image: postgres:17.4
    env_file: .env
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app/
      - ./text_statistics/tf_idf/migrations:/app/text_statistics/tf_idf/migrations
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 --workers 8 text_statistics.wsgi:application
